project:
  type: website
  render:
    - analysis/index.qmd
    - analysis/Nasir/autodetector-normalised.qmd
    - analysis/Najma/project.qmd
    
website:
  navbar:
    left:
      - href: analysis/index.qmd
        text: Home
      - href: analysis/Nasir/autodetector-normalised.qmd
        text: Nasir
      - href: analysis/Najma/project.qmd
        text: Najma

format:
  html:
    theme: cosmo