project:
  type: website
  render:
    - index.qmd
    - analysis/Nasir/autodetector-normalised.qmd
    
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis/Nasir/autodetector-normalised.qmd
        text: Analysis

format:
  html:
    theme: cosmo