project:
  type: website

website:
  title: "My Project"

format:
  html:
    theme: cosmo

navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis\Nasir\autodetector-normalised.qmd
        text: Analysis
     
